config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:typedocument, :document, :code, :fullname, :foto, :active)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :fullname, :profile, :email, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  
  <div class="mb-3">
    <div>
      <%= form.label :typedocument, 'Tipo de documento', style: "display: block" %>
      <%= form.text_field :typedocument, {class: "form-control"} %>
    </div>  
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :document, 'Documento', style: "display: block" %>
      <%= form.text_field :document, {class: "form-control"} %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :code, 'Codigo', style: "display: block" %>
      <%= form.text_field :code, {class: "form-control"} %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :fullname, 'Nombre', style: "display: block" %>
      <%= form.text_field :fullname, {class: "form-control"} %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :foto, 'Foto', style: "display: block" %>
      <%= form.text_field :foto, {class: "form-control"} %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :active, 'Esta activo?', style: "display: block" %>
      <%= form.check_box :active %>
    </div>    
  </div>
  <div>
    <%= form.submit 'Guardar', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<tr id="<%= dom_id student %>">
  <td>
    <%= student.typedocument %>
  </td>

  <td>
    <%= student.document %>
  </td>

  <td>
    <%= student.code %>
  </td>

  <td>
    <%= student.fullname %>
  </td>


  <td>
    <%= link_to "Ver", student %>
  </td>
</tr>

app/views/students/edit.html.erb
<div class="container mx-auto">
  <h1>Editar Estudiante</h1>
  <div>
    <%= render "form", student: @student %>
  </div>

  <div>
    <%= link_to "Ver", @student %> |
    <%= link_to "Volver", students_path %>
  </div>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mx-auto">
  <h1>Estudiantes</h1>
  <%= link_to "Nuevo Estudiante", new_student_path %>
  
  <table id="students" class="table">
    <thead>
      <tr>
        <th scope="col">Tipo Documento</th>
        <th scope="col">Documento</th>
        <th scope="col">Codigo</th>
        <th scope="col">Nombre Completo</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <%= render student %>
      <% end %>
    </tbody>
  </table>

</div>

app/views/students/new.html.erb
<div class="container mx-auto">
  <h1>Crear Estudiante</h1>
  <div>.
  
    <%= render "form", student: @student %>

  </div>
  <div>
    <%= link_to "Volver", students_path %>
  </div>

</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mx-auto">
  <h1><%= @student.fullname %></h1>
  <ul>
    <li><strong>Codigo:</strong> <%= @student.document %>
    <li><strong>Documento:</strong> <%= @student.document %>
    <li><strong>Foto:</strong> <%= @student.foto %>
  </ul>
    
  <%= button_to "Eliminar", @student, method: :delete, class: 'btn btn-outline-danger' %>
  <div>
    <%= link_to "Editar", edit_student_path(@student) %> |
    <%= link_to "Volver", students_path %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <div>
      <%= form.label :username, "Usuario", style: "display: block" %>
      <%= form.text_field :username, { class: "form-control", placeholder: "Ingresa tu usuario" } %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :fullname, "Nombre", style: "display: block" %>
      <%= form.text_field :fullname, { class: "form-control", placeholder: "Ingresa tu nombre completo" } %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :profile, "Perfil", style: "display: block" %>
      <%= form.text_field :profile, { class: "form-control", placeholder: "Escoge tu perfil" } %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :email, "Correo electronico", style: "display: block" %>
      <%= form.text_field :email, { class: "form-control", placeholder: "Ingresa tu correo electronico" } %>
    </div>
  </div>
  <div class="mb-3">
    <div>
      <%= form.label :active, "Esta activo?", style: "display: block" %>
      <%= form.check_box :active %>
    </div>
  </div>
  <div>
    <%= form.submit 'Guardar', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr id="<%= dom_id user %>">

  <td>
    <%= user.username %>
  </td>

  <td>
    <%= user.fullname %>
  </td>

  <td>
    <%= user.profile %>
  </td>

  <td>
    <%= user.email %>
  </td>
  <td>
    <%= link_to "Ver", user %>
  </td>

</tr>

app/views/users/edit.html.erb
<div class="container mx-auto">
  <h1>Editar Usuario</h1>

  <div>
    <%= render "form", user: @user %>
  </div>  
  <div>
    <%= link_to "Mostrar", @user %> |
    <%= link_to "Volver", users_path %>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mx-auto">
  <h1>Usuarios</h1>
  <%= link_to "Nuevo Usuario", new_user_path %>

  <table id="users" class="table">
    <thead>
      <tr>
        <th scope="col">Usuario</th>
        <th scope="col">Nombre</th>
        <th scope="col">Perfil</th>
        <th scope="col">Correo Electronico</th>
        <th scope="col">Acciones</th>

      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <%= render user %>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<div class="container mx-auto">
  <h1>Crear Usuario</h1>
  <div>
    <%= render "form", user: @user %>
  </div>
  <div>
    <%= link_to "Volver", users_path %>
  </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto">
  <h1><%= @user.fullname %></h1>

  <ul>
    <li><strong>Perfil:</strong> <%= @user.profile %></li>
    <li><strong>Correo Electronico: </strong><%= @user.email %></li>
  </ul>

  <%= button_to "Eliminar", @user, method: :delete, class: 'btn btn-outline-danger' %>
  
  <div>
    <%= link_to "Editar", edit_user_path(@user) %> |
    <%= link_to "Atras", users_path %>
  </div>
</div>